/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, PerspectiveCamera, MeshReflectorMaterial, SpotLight, TransformControls } from "@react-three/drei";
import { Bloom, EffectComposer, SSR } from "@react-three/postprocessing"
import { Leva, useControls } from "leva"
import * as THREE from "three";

import { MathUtils, Vector3 } from 'three'
import { Canvas, useFrame, useThree } from '@react-three/fiber'

export default function HQfinal(props) {
    const { nodes, materials } = useGLTF("./hq-room-simple-remeshed10.glb");

    const propsSPOT = useControls({
        penumbra: 1,
        angle: 4,
        distance: 70,
        attenuation: 19,
        anglePower: 7,
        intensity: 2,
        opacity: 0.2,
        color: "white",

    })
    // spotlight
    // penumbra={0.2}
    //     radiusTop={0.4}
    //     radiusBottom={40}
    //     distance={80}
    //     angle={0.45}
    //     attenuation={20}
    //     anglePower={5}
    //     intensity={1}
    //     opacity={0.2}

    const innerSPOT = {
        penumbra: 0,
        angle: 5,
        distance: 70,
        attenuation: 15,
        anglePower: 7,
        intensity: 2,
        color: "white"
    }


    const reflectionPlanes = {
        blur: [1000, 1000],
        resolution: 1024 * 2,
        mixBlur: 1,
        mixStrength: 50,
        roughness: 0.2,
        depthScale: 1.2,
        color: "#1E2F45",
        metalness: 0.8,

    }

    const lightsSpin = useRef()

    console.log(materials["main-metal-reflective"]);
    materials["main-metal-reflective"].roughness = 0.2
    materials["main-metal-reflective"].metalness = 0.8
    materials["main-metal-reflective"].reflectivness = 0
    materials["main-metal-reflective"].color = new THREE.Color(0x1E2F45);



    function MovingSpot({ vec = new Vector3(), ...props }) {
        const light = useRef()
        const viewport = useThree((state) => state.viewport)
        useFrame((state) => {
            light.current.target.position.lerp(vec.set((state.mouse.x * viewport.width) / 2, (state.mouse.y * viewport.height) / 2, 0), 0.1)
            light.current.target.updateMatrixWorld()
        })
        return <SpotLight castShadow ref={light} penumbra={1} distance={6} angle={0.35} attenuation={5} anglePower={4} intensity={2} {...props} />
    }

    useFrame((state, delta) => {
        // console.log(state.camera.position)


        const angle = state.clock.elapsedTime
        const multi = 1

        // state.camera.position.x = -Math.sin(angle + 10) + 10
        // state.camera.position.z = Math.cos(angle + 10)
        // state.camera.lookAt(0, 5, 0)


        lightsSpin.current.position.x = Math.sin(angle * multi)
        lightsSpin.current.position.z = Math.cos(angle * multi)

        lightsSpin.current.lookAt(0, 5, 0)
        // ...
    })



    return (<>
        <group {...props} dispose={null}>
            <MovingSpot color="white" position={[10, 13.3, 4]} castShadow {...innerSPOT} />
            <MovingSpot color="white" position={[-10, 13.3, -4]} castShadow  {...innerSPOT} />

            <group ref={lightsSpin}
            >
                <SpotLight
                    castShadow
                    {...propsSPOT}
                    position={[25, 13, 0]}
                />
                <SpotLight
                    castShadow
                    {...propsSPOT}
                    position={[-25, 13, 0]}
                />
                <SpotLight
                    castShadow
                    {...propsSPOT}
                    position={[0, 13, 25]}
                />
                <SpotLight
                    castShadow
                    {...propsSPOT}
                    position={[0, 13, -25]}
                />
            </group>
            <SpotLight
                castShadow
                {...propsSPOT}
                position={[0, 17.3, 0]}
                color={"darkblue"}
                intensity={9}
                angle={6}
            />

            <spotLight
                name="Spot"
                intensity={1}
                angle={0.85}
                penumbra={1}
                decay={2}

                color="#0000ff"
                position={[0, 17.16, 0]}
                rotation={[-Math.PI / 2, 0, 0]}
            />
            <group name="tiled-outer-plane-parent" position={[0, -0.47, 0]}>

                <mesh
                    name="outer_plate"
                    castShadow
                    receiveShadow
                    geometry={nodes.outer_plate.geometry}
                    material={materials["main-metal-reflective"]}
                    position={[0, 0.47, 0]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.01}
                />
                <mesh
                    name="outer_plate003"
                    castShadow
                    receiveShadow
                    geometry={nodes.outer_plate003.geometry}
                    material={materials["main-metal-reflective"]}
                    position={[0, 0.47, 0]}
                    rotation={[Math.PI / 2, 0, -Math.PI / 6]}
                    scale={0.01}
                />
                <mesh
                    name="outer_plate001"
                    castShadow
                    receiveShadow
                    geometry={nodes.outer_plate001.geometry}
                    material={materials["main-metal-reflective"]}
                    position={[0, 0.47, 0]}
                    rotation={[Math.PI / 2, 0, -0.17]}
                    scale={0.01}
                />
                <mesh
                    name="outer_plate005"
                    castShadow
                    receiveShadow
                    geometry={nodes.outer_plate005.geometry}
                    material={materials["main-metal-reflective"]}
                    position={[0, 0.47, 0]}
                    rotation={[Math.PI / 2, 0, -0.87]}
                    scale={0.01}
                />
                <mesh
                    name="outer_plate002"
                    castShadow
                    receiveShadow
                    geometry={nodes.outer_plate002.geometry}
                    material={materials["main-metal-reflective"]}
                    position={[0, 0.47, 0]}
                    rotation={[Math.PI / 2, 0, -Math.PI / 9]}
                    scale={0.01}
                />
                <mesh
                    name="outer_plate007"
                    castShadow
                    receiveShadow
                    geometry={nodes.outer_plate007.geometry}
                    material={materials["main-metal-reflective"]}
                    position={[0, 0.47, 0]}
                    rotation={[Math.PI / 2, 0, -1.22]}
                    scale={0.01}
                />
                <mesh
                    name="outer_plate004"
                    castShadow
                    receiveShadow
                    geometry={nodes.outer_plate004.geometry}
                    material={materials["main-metal-reflective"]}
                    position={[0, 0.47, 0]}
                    rotation={[Math.PI / 2, 0, -0.7]}
                    scale={0.01}
                />
                <mesh
                    name="outer_plate009"
                    castShadow
                    receiveShadow
                    geometry={nodes.outer_plate009.geometry}
                    material={materials["main-metal-reflective"]}
                    position={[0, 0.47, 0]}
                    rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                    scale={0.01}
                />
                <mesh
                    name="outer_plate006"
                    castShadow
                    receiveShadow
                    geometry={nodes.outer_plate006.geometry}
                    material={materials["main-metal-reflective"]}
                    position={[0, 0.47, 0]}
                    rotation={[Math.PI / 2, 0, -Math.PI / 3]}
                    scale={0.01}
                />
                <mesh
                    name="outer_plate011"
                    castShadow
                    receiveShadow
                    geometry={nodes.outer_plate011.geometry}
                    material={materials["main-metal-reflective"]}
                    position={[0, 0.47, 0]}
                    rotation={[Math.PI / 2, 0, -1.92]}
                    scale={0.01}
                />
                <mesh
                    name="outer_plate013"
                    castShadow
                    receiveShadow
                    geometry={nodes.outer_plate013.geometry}
                    material={materials["main-metal-reflective"]}
                    position={[0, 0.47, 0]}
                    rotation={[Math.PI / 2, 0, -2.27]}
                    scale={0.01}
                />
                <mesh
                    name="outer_plate008"
                    castShadow
                    receiveShadow
                    geometry={nodes.outer_plate008.geometry}
                    material={materials["main-metal-reflective"]}
                    position={[0, 0.47, 0]}
                    rotation={[Math.PI / 2, 0, -1.4]}
                    scale={0.01}
                />
                <mesh
                    name="outer_plate015"
                    castShadow
                    receiveShadow
                    geometry={nodes.outer_plate015.geometry}
                    material={materials["main-metal-reflective"]}
                    position={[0, 0.47, 0]}
                    rotation={[Math.PI / 2, 0, -2.62]}
                    scale={0.01}
                />
                <mesh
                    name="outer_plate017"
                    castShadow
                    receiveShadow
                    geometry={nodes.outer_plate017.geometry}
                    material={materials["main-metal-reflective"]}
                    position={[0, 0.47, 0]}
                    rotation={[Math.PI / 2, 0, -2.97]}
                    scale={0.01}
                />
                <mesh
                    name="outer_plate010"
                    castShadow
                    receiveShadow
                    geometry={nodes.outer_plate010.geometry}
                    material={materials["main-metal-reflective"]}
                    position={[0, 0.47, 0]}
                    rotation={[Math.PI / 2, 0, -1.75]}
                    scale={0.01}
                />
                <mesh
                    name="outer_plate019"
                    castShadow
                    receiveShadow
                    geometry={nodes.outer_plate019.geometry}
                    material={materials["main-metal-reflective"]}
                    position={[0, 0.47, 0]}
                    rotation={[Math.PI / 2, 0, 2.97]}
                    scale={0.01}
                />
                <mesh
                    name="outer_plate012"
                    castShadow
                    receiveShadow
                    geometry={nodes.outer_plate012.geometry}
                    material={materials["main-metal-reflective"]}
                    position={[0, 0.47, 0]}
                    rotation={[Math.PI / 2, 0, -2.09]}
                    scale={0.01}
                />
                <mesh
                    name="outer_plate021"
                    castShadow
                    receiveShadow
                    geometry={nodes.outer_plate021.geometry}
                    material={materials["main-metal-reflective"]}
                    position={[0, 0.47, 0]}
                    rotation={[Math.PI / 2, 0, 2.62]}
                    scale={0.01}
                />
                <mesh
                    name="outer_plate014"
                    castShadow
                    receiveShadow
                    geometry={nodes.outer_plate014.geometry}
                    material={materials["main-metal-reflective"]}
                    position={[0, 0.47, 0]}
                    rotation={[Math.PI / 2, 0, -2.44]}
                    scale={0.01}
                />
                <mesh
                    name="outer_plate023"
                    castShadow
                    receiveShadow
                    geometry={nodes.outer_plate023.geometry}
                    material={materials["main-metal-reflective"]}
                    position={[0, 0.47, 0]}
                    rotation={[Math.PI / 2, 0, 2.27]}
                    scale={0.01}
                />
                <mesh
                    name="outer_plate016"
                    castShadow
                    receiveShadow
                    geometry={nodes.outer_plate016.geometry}
                    material={materials["main-metal-reflective"]}
                    position={[0, 0.47, 0]}
                    rotation={[Math.PI / 2, 0, -2.79]}
                    scale={0.01}
                />
                <mesh
                    name="outer_plate025"
                    castShadow
                    receiveShadow
                    geometry={nodes.outer_plate025.geometry}
                    material={materials["main-metal-reflective"]}
                    position={[0, 0.47, 0]}
                    rotation={[Math.PI / 2, 0, 1.92]}
                    scale={0.01}
                />
                <mesh
                    name="outer_plate018"
                    castShadow
                    receiveShadow
                    geometry={nodes.outer_plate018.geometry}
                    material={materials["main-metal-reflective"]}
                    position={[0, 0.47, 0]}
                    rotation={[Math.PI / 2, 0, -Math.PI]}
                    scale={0.01}
                />
                <mesh
                    name="outer_plate020"
                    castShadow
                    receiveShadow
                    geometry={nodes.outer_plate020.geometry}
                    material={materials["main-metal-reflective"]}
                    position={[0, 0.47, 0]}
                    rotation={[Math.PI / 2, 0, 2.79]}
                    scale={0.01}
                />
                <mesh
                    name="outer_plate027"
                    castShadow
                    receiveShadow
                    geometry={nodes.outer_plate027.geometry}
                    material={materials["main-metal-reflective"]}
                    position={[0, 0.47, 0]}
                    rotation={[Math.PI / 2, 0, Math.PI / 2]}
                    scale={0.01}
                />
                <mesh
                    name="outer_plate022"
                    castShadow
                    receiveShadow
                    geometry={nodes.outer_plate022.geometry}
                    material={materials["main-metal-reflective"]}
                    position={[0, 0.47, 0]}
                    rotation={[Math.PI / 2, 0, 2.44]}
                    scale={0.01}
                />
                <mesh
                    name="outer_plate024"
                    castShadow
                    receiveShadow
                    geometry={nodes.outer_plate024.geometry}
                    material={materials["main-metal-reflective"]}
                    position={[0, 0.47, 0]}
                    rotation={[Math.PI / 2, 0, 2.09]}
                    scale={0.01}
                />
                <mesh
                    name="outer_plate029"
                    castShadow
                    receiveShadow
                    geometry={nodes.outer_plate029.geometry}
                    material={materials["main-metal-reflective"]}
                    position={[0, 0.47, 0]}
                    rotation={[Math.PI / 2, 0, 1.22]}
                    scale={0.01}
                />
                <mesh
                    name="outer_plate026"
                    castShadow
                    receiveShadow
                    geometry={nodes.outer_plate026.geometry}
                    material={materials["main-metal-reflective"]}
                    position={[0, 0.47, 0]}
                    rotation={[Math.PI / 2, 0, 1.75]}
                    scale={0.01}
                />
                <mesh
                    name="outer_plate031"
                    castShadow
                    receiveShadow
                    geometry={nodes.outer_plate031.geometry}
                    material={materials["main-metal-reflective"]}
                    position={[0, 0.47, 0]}
                    rotation={[Math.PI / 2, 0, 0.87]}
                    scale={0.01}
                />
                <mesh
                    name="outer_plate028"
                    castShadow
                    receiveShadow
                    geometry={nodes.outer_plate028.geometry}
                    material={materials["main-metal-reflective"]}
                    position={[0, 0.47, 0]}
                    rotation={[Math.PI / 2, 0, 1.4]}
                    scale={0.01}
                />
                <mesh
                    name="outer_plate033"
                    castShadow
                    receiveShadow
                    geometry={nodes.outer_plate033.geometry}
                    material={materials["main-metal-reflective"]}
                    position={[0, 0.47, 0]}
                    rotation={[Math.PI / 2, 0, Math.PI / 6]}
                    scale={0.01}
                />
                <mesh
                    name="outer_plate030"
                    castShadow
                    receiveShadow
                    geometry={nodes.outer_plate030.geometry}
                    material={materials["main-metal-reflective"]}
                    position={[0, 0.47, 0]}
                    rotation={[Math.PI / 2, 0, Math.PI / 3]}
                    scale={0.01}
                />
                <mesh
                    name="outer_plate035"
                    castShadow
                    receiveShadow
                    geometry={nodes.outer_plate035.geometry}
                    material={materials["main-metal-reflective"]}
                    position={[0, 0.47, 0]}
                    rotation={[Math.PI / 2, 0, 0.17]}
                    scale={0.01}
                />
                <mesh
                    name="outer_plate032"
                    castShadow
                    receiveShadow
                    geometry={nodes.outer_plate032.geometry}
                    material={materials["main-metal-reflective"]}
                    position={[0, 0.47, 0]}
                    rotation={[Math.PI / 2, 0, 0.7]}
                    scale={0.01}
                />
                <mesh
                    name="outer_plate034"
                    castShadow
                    receiveShadow
                    geometry={nodes.outer_plate034.geometry}
                    material={materials["main-metal-reflective"]}
                    position={[0, 0.47, 0]}
                    rotation={[Math.PI / 2, 0, Math.PI / 9]}
                    scale={0.01}
                />
            </group>
            <PerspectiveCamera
                name="main-cam"
                makeDefault={false}
                far={1000}
                near={0.1}
                fov={20.41}
                position={[3.56, 10.07, 34.95]}
                rotation={[-0.13, 0.13, 0.02]}
            />
            <spotLight
                name="Spot"
                intensity={1}
                angle={0.85}
                penumbra={0.15}
                decay={2}
                color="#ff0009"
                position={[0, 17.16, 0]}
                rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
                name="Circle"
                castShadow
                receiveShadow
                geometry={nodes.Circle.geometry}
                material={materials["main-metal-reflective"]}
                scale={37.91}
            />
            <mesh
                name="light-plane"
                castShadow
                receiveShadow
                geometry={nodes["light-plane"].geometry}
                material={materials.top_light}
            />
            <mesh
                name="Mesh004"
                castShadow
                receiveShadow
                geometry={nodes.Mesh004.geometry}
                material={materials["main-metal-reflective"]}
            />
            <mesh
                name="Mesh004_1"
                castShadow
                receiveShadow
                geometry={nodes.Mesh004_1.geometry}
                material={materials.white_ambient_light}
            />
            <group name="table" position={[0.42, 0.25, -7.02]}>
                <mesh
                    name="Mesh072"
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh072.geometry}
                    material={nodes.Mesh072.material}
                />
                <mesh
                    name="Mesh072_1"
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh072_1.geometry}
                    material={materials["main-metal-reflective"]}
                />
            </group>
            <mesh
                name="Mesh054"
                castShadow
                receiveShadow
                geometry={nodes.Mesh054.geometry}
                material={materials["main-metal-reflective"]}
            />
            <mesh
                name="Mesh054_1"
                castShadow
                receiveShadow
                geometry={nodes.Mesh054_1.geometry}
                material={materials.white_ambient_light}
            />
            <mesh
                name="table_base"
                castShadow
                receiveShadow
                geometry={nodes.table_base.geometry}
                material={materials["main-metal-reflective"]}
                position={[0.42, 0.25, -7.02]}
            />
            <mesh
                name="inner-collection002"
                castShadow
                receiveShadow
                geometry={nodes["inner-collection002"].geometry}
                material={materials["main-metal-reflective"]}
            />
            <mesh
                name="outer-stuff001"
                castShadow
                receiveShadow
                geometry={nodes["outer-stuff001"].geometry}
                material={materials["main-metal-reflective"]}
            />
            <mesh
                name="vent-flaps"
                castShadow
                receiveShadow
                geometry={nodes["vent-flaps"].geometry}
                material={nodes["vent-flaps"].material}
                position={[0, 6.64, 0]}
            />
            <mesh
                name="center-lamp"
                castShadow
                receiveShadow
                geometry={nodes["center-lamp"].geometry}
                material={materials["main-metal-reflective"]}
                position={[0, 8.95, -3.51]}
            />
            <mesh
                name="decoration"
                castShadow
                receiveShadow
                geometry={nodes.decoration.geometry}
                material={materials["main-metal-reflective"]}
            />
            <group name="outer-tubes" position={[0, 8.95, -3.51]}>
                <mesh
                    name="Mesh047"
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh047.geometry}
                    material={materials["main-metal-reflective"]}
                />
                <mesh
                    name="Mesh047_1"
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh047_1.geometry}
                    material={materials.white_ambient_light}
                />
            </group>
            <mesh
                name="decoration001"
                castShadow
                receiveShadow
                geometry={nodes.decoration001.geometry}
                material={materials["main-metal-reflective"]}
                rotation={[0, 1.26, 0]}
            />
            <mesh
                name="decoration002"
                castShadow
                receiveShadow
                geometry={nodes.decoration002.geometry}
                material={materials["main-metal-reflective"]}
                rotation={[-Math.PI, Math.PI / 5, -Math.PI]}
            />
            <group name="cake-slice-decoration001" rotation={[0, -0.05, 0]}>
                <mesh
                    name="Mesh062"
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh062.geometry}
                    material={materials["main-metal-reflective"]}
                />
                <mesh
                    name="Mesh062_1"
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh062_1.geometry}
                    material={materials.white_ambient_light}
                />
            </group>
            <mesh
                name="decoration004"
                castShadow
                receiveShadow
                geometry={nodes.decoration004.geometry}
                material={materials["main-metal-reflective"]}
                rotation={[0, -1.26, 0]}
            />
            <mesh
                name="vent-flaps003"
                castShadow
                receiveShadow
                geometry={nodes["vent-flaps003"].geometry}
                material={nodes["vent-flaps003"].material}
                position={[0, 6.64, 0]}
                rotation={[Math.PI, -Math.PI / 5, Math.PI]}
            />
            <mesh
                name="decoration003"
                castShadow
                receiveShadow
                geometry={nodes.decoration003.geometry}
                material={materials["main-metal-reflective"]}
                rotation={[Math.PI, -Math.PI / 5, Math.PI]}
            />
            <mesh
                name="vent-flaps001"
                castShadow
                receiveShadow
                geometry={nodes["vent-flaps001"].geometry}
                material={nodes["vent-flaps001"].material}
                position={[0, 6.64, 0]}
                rotation={[0, 1.26, 0]}
            />
            <mesh
                name="vent-flaps002"
                castShadow
                receiveShadow
                geometry={nodes["vent-flaps002"].geometry}
                material={nodes["vent-flaps002"].material}
                position={[0, 6.64, 0]}
                rotation={[-Math.PI, Math.PI / 5, -Math.PI]}
            />
            <mesh
                name="vent-flaps004"
                castShadow
                receiveShadow
                geometry={nodes["vent-flaps004"].geometry}
                material={nodes["vent-flaps004"].material}
                position={[0, 6.64, 0]}
                rotation={[0, -1.26, 0]}
            />
            <group name="cake-slice-decoration002" rotation={[0, 1.2, 0]}>
                <mesh
                    name="Mesh079"
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh079.geometry}
                    material={materials["main-metal-reflective"]}
                />
                <mesh
                    name="Mesh079_1"
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh079_1.geometry}
                    material={materials.white_ambient_light}
                />
            </group>
            <group
                name="cake-slice-decoration003"
                rotation={[-Math.PI, 0.68, -Math.PI]}
            >
                <mesh
                    name="Mesh080"
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh080.geometry}
                    material={materials["main-metal-reflective"]}
                />
                <mesh
                    name="Mesh080_1"
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh080_1.geometry}
                    material={materials.white_ambient_light}
                />
            </group>
            <group
                name="cake-slice-decoration004"
                rotation={[Math.PI, -0.58, Math.PI]}
            >
                <mesh
                    name="Mesh081"
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh081.geometry}
                    material={materials["main-metal-reflective"]}
                />
                <mesh
                    name="Mesh081_1"
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh081_1.geometry}
                    material={materials.white_ambient_light}
                />
            </group>
            <mesh
                name="Mesh036"
                castShadow
                receiveShadow
                geometry={nodes.Mesh036.geometry}
                material={materials["main-metal-reflective"]}
            />
            <mesh
                name="Mesh036_1"
                castShadow
                receiveShadow
                geometry={nodes.Mesh036_1.geometry}
                material={materials.white_ambient_light}
            />
            <group name="cake-slice-decoration005" rotation={[0, -1.31, 0]}>
                <mesh
                    name="Mesh082"
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh082.geometry}
                    material={materials["main-metal-reflective"]}
                />
                <mesh
                    name="Mesh082_1"
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh082_1.geometry}
                    material={materials.white_ambient_light}
                />
            </group>
            <mesh
                name="table001"
                castShadow
                receiveShadow
                geometry={nodes.table001.geometry}
                material={materials["display Table"]}
                position={[0.42, 0.25, -7.02]}
            />
            <group name="cake-slice-filler003" rotation={[0, -1.26, 0]}>
                <mesh
                    name="Mesh057"
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh057.geometry}
                    material={materials["main-metal-reflective"]}
                />
                <mesh
                    name="Mesh057_1"
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh057_1.geometry}
                    material={materials.white_ambient_light}
                />
            </group>
        </group>
    </>
    );
}

useGLTF.preload("./hq-room-simple-remeshed10.glb");
