/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { MeshReflectorMaterial, useGLTF } from "@react-three/drei";

export default function C(props) {
    const { nodes, materials } = useGLTF("./testing_c.glb");
    return (
        <group {...props} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                scale={100}
                rotation={[11, 0, 0]}
            >
                <circleGeometry />
                <MeshReflectorMaterial
                    blur={[1000, 1000]}
                    resolution={2048}
                    mixBlur={1}
                    mixStrength={50}
                    roughness={1}
                    depthScale={1.2}
                    color="#050505"
                    metalness={0.5}
                />

            </mesh>

        </group>
    );
}

useGLTF.preload("./testing_c.glb");