/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, PerspectiveCamera, MeshReflectorMaterial, SpotLight } from "@react-three/drei";
import { Bloom, EffectComposer, SSR } from "@react-three/postprocessing"
import { Leva, useControls } from "leva"
import * as THREE from "three";

export default function HQ(props) {
    const { nodes, materials } = useGLTF("./hq_remeshed_1.glb");
    const model = useGLTF("./hq-room-simple1.glb");
    console.log("🚀 ~ HQ ~ model:", model)
    console.log("🚀 ~ HQ ~ materials:", materials)

    // materials.getObjectByName("Material.004")

    console.log("🚀 ~ HQ ~  materials.white_ambient_light:", materials.white_ambient_light)
    materials.white_ambient_light.color = new THREE.Color(0, 1, 0);
    console.log("🚀 ~ HQ ~ materials.white_ambient_light.color:", materials.white_ambient_light.color)


    const propsSSR = useControls({
        temporalResolve: true,
        STRETCH_MISSED_RAYS: true,
        USE_MRT: true,
        USE_NORMALMAP: true,
        USE_ROUGHNESSMAP: true,
        ENABLE_JITTERING: true,
        ENABLE_BLUR: true,
        temporalResolveMix: { value: 0.9, min: 0, max: 1 },
        temporalResolveCorrectionMix: { value: 0.25, min: 0, max: 1 },
        maxSamples: { value: 0, min: 0, max: 1 },
        resolutionScale: { value: 1, min: 0, max: 1 },
        blurMix: { value: 0.5, min: 0, max: 1 },
        blurKernelSize: { value: 8, min: 0, max: 8 },
        blurSharpness: { value: 0.5, min: 0, max: 1 },
        rayStep: { value: 0.3, min: 0, max: 1 },
        intensity: { value: 1, min: 0, max: 5 },
        maxRoughness: { value: 0.1, min: 0, max: 1 },
        jitter: { value: 0.7, min: 0, max: 5 },
        jitterSpread: { value: 0.45, min: 0, max: 1 },
        jitterRough: { value: 0.1, min: 0, max: 1 },
        roughnessFadeOut: { value: 1, min: 0, max: 1 },
        rayFadeOut: { value: 0, min: 0, max: 1 },
        MAX_STEPS: { value: 20, min: 0, max: 20 },
        NUM_BINARY_SEARCH_STEPS: { value: 5, min: 0, max: 10 },
        maxDepthDifference: { value: 3, min: 0, max: 10 },
        maxDepth: { value: 1, min: 0, max: 1 },
        thickness: { value: 10, min: 0, max: 10 },
        ior: { value: 1.45, min: 0, max: 2 }
    })
    return (<>
        <EffectComposer disableNormalPass>
            <Bloom luminanceThreshold={0.2} mipmapBlur luminanceSmoothing={0} intensity={1.75} />

        </EffectComposer>

        <group {...props} dispose={null}>
            <SpotLight
                distance={5}
                angle={0.15}
                attenuation={5}
                anglePower={5} // Diffuse-cone anglePower (default: 5)
            />
            <group name="tiled-outer-plane-parent" position={[0, -0.47, 0]}>
                <mesh
                    name="outer_plate"
                    castShadow
                    receiveShadow
                    geometry={nodes.outer_plate.geometry}
                    material={materials["main-metal-reflective"]}
                    position={[0, 0.47, 0]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.01}
                />
                <mesh
                    name="outer_plate001"
                    castShadow
                    receiveShadow
                    geometry={nodes.outer_plate001.geometry}
                    material={materials["main-metal-reflective"]}
                    position={[0, 0.47, 0]}
                    rotation={[Math.PI / 2, 0, -0.17]}
                    scale={0.01}
                />
                <mesh
                    name="outer_plate002"
                    castShadow
                    receiveShadow
                    geometry={nodes.outer_plate002.geometry}
                    material={materials["main-metal-reflective"]}
                    position={[0, 0.47, 0]}
                    rotation={[Math.PI / 2, 0, -Math.PI / 9]}
                    scale={0.01}
                />
                <mesh
                    name="outer_plate003"
                    castShadow
                    receiveShadow
                    geometry={nodes.outer_plate003.geometry}
                    material={materials["main-metal-reflective"]}
                    position={[0, 0.47, 0]}
                    rotation={[Math.PI / 2, 0, -Math.PI / 6]}
                    scale={0.01}
                />
                <mesh
                    name="outer_plate004"
                    castShadow
                    receiveShadow
                    geometry={nodes.outer_plate004.geometry}
                    material={materials["main-metal-reflective"]}
                    position={[0, 0.47, 0]}
                    rotation={[Math.PI / 2, 0, -0.7]}
                    scale={0.01}
                />
                <mesh
                    name="outer_plate005"
                    castShadow
                    receiveShadow
                    geometry={nodes.outer_plate005.geometry}
                    material={materials["main-metal-reflective"]}
                    position={[0, 0.47, 0]}
                    rotation={[Math.PI / 2, 0, -0.87]}
                    scale={0.01}
                />
                <mesh
                    name="outer_plate006"
                    castShadow
                    receiveShadow
                    geometry={nodes.outer_plate006.geometry}
                    material={materials["main-metal-reflective"]}
                    position={[0, 0.47, 0]}
                    rotation={[Math.PI / 2, 0, -Math.PI / 3]}
                    scale={0.01}
                />
                <mesh
                    name="outer_plate007"
                    castShadow
                    receiveShadow
                    geometry={nodes.outer_plate007.geometry}
                    material={materials["main-metal-reflective"]}
                    position={[0, 0.47, 0]}
                    rotation={[Math.PI / 2, 0, -1.22]}
                    scale={0.01}
                />
                <mesh
                    name="outer_plate008"
                    castShadow
                    receiveShadow
                    geometry={nodes.outer_plate008.geometry}
                    material={materials["main-metal-reflective"]}
                    position={[0, 0.47, 0]}
                    rotation={[Math.PI / 2, 0, -1.4]}
                    scale={0.01}
                />
                <mesh
                    name="outer_plate009"
                    castShadow
                    receiveShadow
                    geometry={nodes.outer_plate009.geometry}
                    material={materials["main-metal-reflective"]}
                    position={[0, 0.47, 0]}
                    rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                    scale={0.01}
                />
                <mesh
                    name="outer_plate010"
                    castShadow
                    receiveShadow
                    geometry={nodes.outer_plate010.geometry}
                    material={materials["main-metal-reflective"]}
                    position={[0, 0.47, 0]}
                    rotation={[Math.PI / 2, 0, -1.75]}
                    scale={0.01}
                />
                <mesh
                    name="outer_plate012"
                    castShadow
                    receiveShadow
                    geometry={nodes.outer_plate012.geometry}
                    material={materials["main-metal-reflective"]}
                    position={[0, 0.47, 0]}
                    rotation={[Math.PI / 2, 0, -2.09]}
                    scale={0.01}
                />
                <mesh
                    name="outer_plate014"
                    castShadow
                    receiveShadow
                    geometry={nodes.outer_plate014.geometry}
                    material={materials["main-metal-reflective"]}
                    position={[0, 0.47, 0]}
                    rotation={[Math.PI / 2, 0, -2.44]}
                    scale={0.01}
                />
                <mesh
                    name="outer_plate016"
                    castShadow
                    receiveShadow
                    geometry={nodes.outer_plate016.geometry}
                    material={materials["main-metal-reflective"]}
                    position={[0, 0.47, 0]}
                    rotation={[Math.PI / 2, 0, -2.79]}
                    scale={0.01}
                />
                <mesh
                    name="outer_plate018"
                    castShadow
                    receiveShadow
                    geometry={nodes.outer_plate018.geometry}
                    material={materials["main-metal-reflective"]}
                    position={[0, 0.47, 0]}
                    rotation={[Math.PI / 2, 0, -Math.PI]}
                    scale={0.01}
                />
                <mesh
                    name="outer_plate020"
                    castShadow
                    receiveShadow
                    geometry={nodes.outer_plate020.geometry}
                    material={materials["main-metal-reflective"]}
                    position={[0, 0.47, 0]}
                    rotation={[Math.PI / 2, 0, 2.79]}
                    scale={0.01}
                />
                <mesh
                    name="outer_plate022"
                    castShadow
                    receiveShadow
                    geometry={nodes.outer_plate022.geometry}
                    material={materials["main-metal-reflective"]}
                    position={[0, 0.47, 0]}
                    rotation={[Math.PI / 2, 0, 2.44]}
                    scale={0.01}
                />
                <mesh
                    name="outer_plate024"
                    castShadow
                    receiveShadow
                    geometry={nodes.outer_plate024.geometry}
                    material={materials["main-metal-reflective"]}
                    position={[0, 0.47, 0]}
                    rotation={[Math.PI / 2, 0, 2.09]}
                    scale={0.01}
                />
                <mesh
                    name="outer_plate026"
                    castShadow
                    receiveShadow
                    geometry={nodes.outer_plate026.geometry}
                    material={materials["main-metal-reflective"]}
                    position={[0, 0.47, 0]}
                    rotation={[Math.PI / 2, 0, 1.75]}
                    scale={0.01}
                />
                <mesh
                    name="outer_plate028"
                    castShadow
                    receiveShadow
                    geometry={nodes.outer_plate028.geometry}
                    material={materials["main-metal-reflective"]}
                    position={[0, 0.47, 0]}
                    rotation={[Math.PI / 2, 0, 1.4]}
                    scale={0.01}
                />
                <mesh
                    name="outer_plate030"
                    castShadow
                    receiveShadow
                    geometry={nodes.outer_plate030.geometry}
                    material={materials["main-metal-reflective"]}
                    position={[0, 0.47, 0]}
                    rotation={[Math.PI / 2, 0, Math.PI / 3]}
                    scale={0.01}
                />
                <mesh
                    name="outer_plate032"
                    castShadow
                    receiveShadow
                    geometry={nodes.outer_plate032.geometry}
                    material={materials["main-metal-reflective"]}
                    position={[0, 0.47, 0]}
                    rotation={[Math.PI / 2, 0, 0.7]}
                    scale={0.01}
                />
                <mesh
                    name="outer_plate011"
                    castShadow
                    receiveShadow
                    geometry={nodes.outer_plate011.geometry}
                    material={materials["main-metal-reflective"]}
                    position={[0, 0.47, 0]}
                    rotation={[Math.PI / 2, 0, -1.92]}
                    scale={0.01}
                />
                <mesh
                    name="outer_plate034"
                    castShadow
                    receiveShadow
                    geometry={nodes.outer_plate034.geometry}
                    material={materials["main-metal-reflective"]}
                    position={[0, 0.47, 0]}
                    rotation={[Math.PI / 2, 0, Math.PI / 9]}
                    scale={0.01}
                />
                <mesh
                    name="outer_plate013"
                    castShadow
                    receiveShadow
                    geometry={nodes.outer_plate013.geometry}
                    material={materials["main-metal-reflective"]}
                    position={[0, 0.47, 0]}
                    rotation={[Math.PI / 2, 0, -2.27]}
                    scale={0.01}
                />
                <mesh
                    name="outer_plate015"
                    castShadow
                    receiveShadow
                    geometry={nodes.outer_plate015.geometry}
                    material={materials["main-metal-reflective"]}
                    position={[0, 0.47, 0]}
                    rotation={[Math.PI / 2, 0, -2.62]}
                    scale={0.01}
                />
                <mesh
                    name="outer_plate017"
                    castShadow
                    receiveShadow
                    geometry={nodes.outer_plate017.geometry}
                    material={materials["main-metal-reflective"]}
                    position={[0, 0.47, 0]}
                    rotation={[Math.PI / 2, 0, -2.97]}
                    scale={0.01}
                />
                <mesh
                    name="outer_plate019"
                    castShadow
                    receiveShadow
                    geometry={nodes.outer_plate019.geometry}
                    material={materials["main-metal-reflective"]}
                    position={[0, 0.47, 0]}
                    rotation={[Math.PI / 2, 0, 2.97]}
                    scale={0.01}
                />
                <mesh
                    name="outer_plate021"
                    castShadow
                    receiveShadow
                    geometry={nodes.outer_plate021.geometry}
                    material={materials["main-metal-reflective"]}
                    position={[0, 0.47, 0]}
                    rotation={[Math.PI / 2, 0, 2.62]}
                    scale={0.01}
                />
                <mesh
                    name="outer_plate023"
                    castShadow
                    receiveShadow
                    geometry={nodes.outer_plate023.geometry}
                    material={materials["main-metal-reflective"]}
                    position={[0, 0.47, 0]}
                    rotation={[Math.PI / 2, 0, 2.27]}
                    scale={0.01}
                />
                <mesh
                    name="outer_plate025"
                    castShadow
                    receiveShadow
                    geometry={nodes.outer_plate025.geometry}
                    material={materials["main-metal-reflective"]}
                    position={[0, 0.47, 0]}
                    rotation={[Math.PI / 2, 0, 1.92]}
                    scale={0.01}
                />
                <mesh
                    name="outer_plate027"
                    castShadow
                    receiveShadow
                    geometry={nodes.outer_plate027.geometry}
                    material={materials["main-metal-reflective"]}
                    position={[0, 0.47, 0]}
                    rotation={[Math.PI / 2, 0, Math.PI / 2]}
                    scale={0.01}
                />
                <mesh
                    name="outer_plate029"
                    castShadow
                    receiveShadow
                    geometry={nodes.outer_plate029.geometry}
                    material={materials["main-metal-reflective"]}
                    position={[0, 0.47, 0]}
                    rotation={[Math.PI / 2, 0, 1.22]}
                    scale={0.01}
                />
                <mesh
                    name="outer_plate031"
                    castShadow
                    receiveShadow
                    geometry={nodes.outer_plate031.geometry}
                    material={materials["main-metal-reflective"]}
                    position={[0, 0.47, 0]}
                    rotation={[Math.PI / 2, 0, 0.87]}
                    scale={0.01}
                />
                <mesh
                    name="outer_plate033"
                    castShadow
                    receiveShadow
                    geometry={nodes.outer_plate033.geometry}
                    material={materials["main-metal-reflective"]}
                    position={[0, 0.47, 0]}
                    rotation={[Math.PI / 2, 0, Math.PI / 6]}
                    scale={0.01}
                />
                <mesh
                    name="outer_plate035"
                    castShadow
                    receiveShadow
                    geometry={nodes.outer_plate035.geometry}
                    material={materials["main-metal-reflective"]}
                    position={[0, 0.47, 0]}
                    rotation={[Math.PI / 2, 0, 0.17]}
                    scale={0.01}
                />
            </group>
            <spotLight
                name="Point"
                intensity={0}
                decay={1}
                position={[0, 14, 0]}
                rotation={[-Math.PI / 2, 0, 0]}
                color={"lightblue"}
            />
            <PerspectiveCamera
                name="main-cam"
                makeDefault={false}
                far={1000}
                near={0.1}
                fov={20.41}
                position={[0, 20, 80]}
                rotation={[-0.26, 0, 0]}
            />
            <mesh
                name="big_floor"
                castShadow
                receiveShadow
                geometry={nodes.big_floor.geometry}
                material={nodes.big_floor.material}
                position={[0, -0.47, 0]}
                scale={41.62}
            />

            <mesh
                name="light-plane"
                castShadow
                receiveShadow
                geometry={nodes["light-plane"].geometry}
                material={materials.top_light}
                position={[0, 8.95, -3.51]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={0.01}
            />
            <group name="inner-floor" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
                <mesh
                    name="Mesh004"
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh004.geometry}
                    material={materials["main-metal-reflective"]}
                />
                <mesh
                    name="Mesh004_1"
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh004_1.geometry}
                    material={materials.white_ambient_light}
                />
            </group>
            <mesh
                name="table_base"
                castShadow
                receiveShadow
                geometry={nodes.table_base.geometry}
                material={materials["main-metal-reflective"]}
                position={[0.42, 0.25, -7.02]}
                scale={0.05}
            />
            <mesh
                name="outer-stuff001"
                castShadow
                receiveShadow
                geometry={nodes["outer-stuff001"].geometry}
                material={materials["main-metal-reflective"]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={0.01}
            />
            <mesh
                name="Cube"
                castShadow
                receiveShadow
                geometry={nodes.Cube.geometry}
                material={nodes.Cube.material}
                position={[0, 6.64, 0]}
            />
            <mesh
                name="outer-stuff004"
                castShadow
                receiveShadow
                geometry={nodes["outer-stuff004"].geometry}
                material={materials["main-metal-reflective"]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={0.01}
            />
            <mesh
                name="outer-stuff005"
                castShadow
                receiveShadow
                geometry={nodes["outer-stuff005"].geometry}
                material={materials["main-metal-reflective"]}
                position={[0, 8.95, -3.51]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={0.01}
            />
            <group
                name="outer-stuff003"
                position={[0, 8.95, -3.51]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={0.01}
            >
                <mesh
                    name="Mesh047"
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh047.geometry}
                    material={materials["main-metal-reflective"]}
                />
                <mesh
                    name="Mesh047_1"
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh047_1.geometry}
                    material={materials.white_ambient_light}
                />
            </group>
            <group name="outer-stuff006" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>

                <mesh
                    name="Mesh051_1"
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh051_1.geometry}
                    material={materials.white_ambient_light}
                />
            </group>
            <group
                name="outer-stuff002"
                position={[0, 8.95, -3.51]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={0.01}
            >

                <mesh
                    name="Mesh046_1"
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh046_1.geometry}
                    material={materials.white_ambient_light}
                />
            </group>
            <group name="table" position={[0.42, 0.25, -7.02]} scale={0.05}>
                <mesh
                    name="Mesh072"
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh072.geometry}
                    material={nodes.Mesh072.material}
                />
                <mesh
                    name="Mesh072_1"
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh072_1.geometry}
                    material={materials["display Table"]}
                />
                <mesh
                    name="Mesh072_2"
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh072_2.geometry}
                    material={materials["main-metal-reflective"]}
                />
            </group>
            <group
                name="inner-collection"
                rotation={[Math.PI / 2, 0, 0]}
                scale={0.01}
            >
                <mesh
                    name="Mesh036"
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh036.geometry}
                    material={materials["main-metal-reflective"]}
                />
                <mesh
                    name="Mesh036_1"
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh036_1.geometry}
                    material={materials.white_ambient_light}
                />
            </group>
        </group>
    </>
    );

}

useGLTF.preload("./hq_remeshed_1.glb");
