/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, PerspectiveCamera } from "@react-three/drei";
import * as THREE from "three";

export default function HQ13(props) {
    const { nodes, materials } = useGLTF("./hq-room-simple-remeshed13.glb");

    materials["main-metal-reflective"].roughness = 0.2
    materials["main-metal-reflective"].metalness = 0.8
    materials["main-metal-reflective"].reflectivness = 0
    materials["main-metal-reflective"].color = new THREE.Color(0x1E2F45);


    return (
        <group {...props} dispose={null}>
            <PerspectiveCamera
                name="main-cam"
                makeDefault={false}
                far={1000}
                near={0.1}
                fov={20.41}
                position={[-26.69, 2.93, 36.64]}
                rotation={[-0.01, -0.63, 0]}
            />
            {/* <spotLight
                name="Spot"
                intensity={1.06}
                angle={0.85}
                penumbra={0.15}
                decay={2}
                color="#ff0009"
                position={[0, 17.16, 0]}
                rotation={[-Math.PI / 2, 0, 0]}
            /> */}
            <mesh
                name="Chair_part_2001"
                castShadow
                receiveShadow
                geometry={nodes.Chair_part_2001.geometry}
                material={materials["Material #32"]}
                position={[0, 4.51, 0]}
                scale={0.05}
            />
            <mesh
                name="light-plane"
                castShadow
                receiveShadow
                geometry={nodes["light-plane"].geometry}
                material={materials.top_light}
            />
            <group name="table" position={[0.42, 0.08, -7.02]}>
                <mesh
                    name="Mesh072"
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh072.geometry}
                    material={nodes.Mesh072.material}
                />
                <mesh
                    name="Mesh072_1"
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh072_1.geometry}
                    material={materials["main-metal-reflective"]}
                />
            </group>
            <mesh
                name="Mesh004"
                castShadow
                receiveShadow
                geometry={nodes.Mesh004.geometry}
                material={materials["main-metal-reflective"]}
            />
            <mesh
                name="Mesh004_1"
                castShadow
                receiveShadow
                geometry={nodes.Mesh004_1.geometry}
                material={materials.white_ambient_light}
            />
            <mesh

                name="table_base"
                castShadow
                receiveShadow
                geometry={nodes.table_base.geometry}
                material={materials["main-metal-reflective"]}
                position={[0.42, 0.08, -7.02]}
            />
            <mesh
                name="Mesh054"
                castShadow
                receiveShadow
                geometry={nodes.Mesh054.geometry}
                material={materials["main-metal-reflective"]}
            />
            <mesh
                name="Mesh054_1"
                castShadow
                receiveShadow
                geometry={nodes.Mesh054_1.geometry}
                material={materials.white_ambient_light}
            />
            <mesh
                name="outer_plate"
                castShadow
                receiveShadow
                geometry={nodes.outer_plate.geometry}
                material={materials["main-metal-reflective"]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={0.01}
            />
            <mesh
                name="big-floor"
                castShadow
                receiveShadow
                geometry={nodes["big-floor"].geometry}
                material={materials["main-metal-reflective"]}
                scale={37.91}
            />
            <mesh
                name="Mesh055"
                castShadow
                receiveShadow
                geometry={nodes.Mesh055.geometry}
                material={materials["main-metal-reflective"]}
            />
            <mesh
                name="Mesh055_1"
                castShadow
                receiveShadow
                geometry={nodes.Mesh055_1.geometry}
                material={materials.white_ambient_light}
            />
            <mesh
                name="center-lamp"
                castShadow
                receiveShadow
                geometry={nodes["center-lamp"].geometry}
                material={materials["main-metal-reflective"]}
                position={[0, 8.95, -3.51]}
            />
            <mesh
                name="outer-structure"
                castShadow
                receiveShadow
                geometry={nodes["outer-structure"].geometry}
                material={materials["main-metal-reflective"]}
            />
            <group name="cake-slice-decoration" rotation={[0, -1.31, 0]}>
                <mesh
                    name="Mesh082"
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh082.geometry}
                    material={materials["main-metal-reflective"]}
                />
                <mesh
                    name="Mesh082_1"
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh082_1.geometry}
                    material={materials.white_ambient_light}
                />
            </group>
            <mesh
                name="Mesh036"
                castShadow
                receiveShadow
                geometry={nodes.Mesh036.geometry}
                material={materials["main-metal-reflective"]}
            />
            <mesh
                name="Mesh036_1"
                castShadow
                receiveShadow
                geometry={nodes.Mesh036_1.geometry}
                material={materials.white_ambient_light}
            />
            <mesh
                name="table001"
                castShadow
                receiveShadow
                geometry={nodes.table001.geometry}
                material={materials["display Table"]}
                position={[0.42, 0.08, -7.02]}
            />
            <group name="outer-structure-decoration" rotation={[0, -1.26, 0]}>
                <mesh
                    name="Mesh057"
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh057.geometry}
                    material={materials["main-metal-reflective"]}
                />
                <mesh
                    name="Mesh057_1"
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh057_1.geometry}
                    material={materials.white_ambient_light}
                />
            </group>
        </group>
    );
}

useGLTF.preload("./hq-room-simple-remeshed13.glb");