/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState } from "react";
import { useGLTF, useCursor } from "@react-three/drei";
import * as THREE from 'three'
import gsap from "gsap";
import { useThree } from "@react-three/fiber";



export default function Pig(props) {
    const { nodes, materials } = useGLTF("./pig-lowPoly.glb");
    const [hovered, setHovered] = useState(false)
    useCursor(hovered)


    return (
        <group castShadow recieveShadow {...props} dispose={null}

        >
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Hacker_Pig_2037.geometry}
                material={materials.Pupil}
                position={[0, 2.23, 0.87]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={0.01}

            />
            <group
                position={[0, 2.23, 0.83]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={0.01}
            >
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh045.geometry}
                    material={materials.Sclera}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh045_1.geometry}
                    material={materials.Eyebrows}
                />
            </group>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Sphere011.geometry}
                material={nodes.Sphere011.material}
                position={[0, 2.86, 0.87]}
                scale={[1.55, 1.37, 1.3]}
            />
        </group>
    );
}


const clicked = (p) => {
    console.log(p);
}

const hoverin = (p) => {
    console.log(p);
    // p.object.material.color = new THREE.Color("blue")
    gsap.to(p.object.material.color, {
        r: 1,
        g: 0,
        b: 0,
        duration: 2
    })

    console.log(p.object.material.color);

}


const hoverout = (p) => {
    p.object.material.color = new THREE.Color(0xf0f0f0)
}


useGLTF.preload("./pig-lowPoly.glb");
