/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

import * as THREE from "three"
export default function Planet(props) {
    const group = useRef();
    const { nodes, materials, animations } = useGLTF(
        "./Animated_Hologram_Planet_Earth_Sci-Fi_3D_Model_4k_Textures.glb"
    );
    const animation = useAnimations(animations, group);

    useEffect(() => {
        const action = animation.actions["Action"]
        action.play()
    })

    const mat = materials.EarthHologram
    console.log("mat", mat);
    mat.emissive = new THREE.Color(0xff0000)
    mat.emissiveIntensity = 1
    mat.color = new THREE.Color(0xff0000)
    mat.wireframe = false



    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Scene">
                <group name="Armature">
                    <primitive object={nodes.Master} />
                    <group name="Planet_1">
                        <skinnedMesh
                            name="Sphere"
                            geometry={nodes.Sphere.geometry}
                            material={materials.EarthHologram}
                            skeleton={nodes.Sphere.skeleton}
                        />
                    </group>
                </group>
            </group>
        </group>
    );
}

useGLTF.preload(
    "./Animated_Hologram_Planet_Earth_Sci-Fi_3D_Model_4k_Textures.glb"
);
